service: discourse

frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  stage: "${opt:stage, self:provider.stage}"
  kmsKeyArn: ${file(env.yml):${self:custom.stage}.KEY_ARN}

provider:
  name: aws
  runtime: python3.6
  timeout: 180
  environment: ${file(env.yml):${self:custom.stage}}
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action:
        - KMS:Decrypt
      Resource:
        - ${self:custom.kmsKeyArn}

plugins:
  - serverless-python-requirements

functions:
  user-events:
      name: Discourse-UserEventsWebHook
      handler: handler.user_events
      events:
        - http: POST DiscourseEvents

package:
  exclude:
    - node_modules/**
    - a/**
    - .git/**
