service: discourse

frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  stage: "${opt:stage, self:provider.stage}"
  kmsKeyArn: ${file(env.yml):${self:custom.stage}.KEY_ARN}
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  timeout: 180
  environment: ${file(env.yml):${self:custom.stage}}
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action:
        - KMS:Decrypt
      Resource:
        - ${self:custom.kmsKeyArn}
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "arn:aws:ssm:*:715633473519:parameter/com.neo4j.devrel.discourse.*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "arn:aws:ssm:*:715633473519:parameter/com.neo4j.graphacademy.*"

plugins:
  - serverless-python-requirements

functions:
  community-content:
      name: Discourse-CommunityContentWebHook
      handler: handler.community_content
      timeout: 30
      events:
        - http: POST CommunityContent
  user-events:
      name: Discourse-UserEventsWebHook
      handler: handler.user_events
      timeout: 30
      events:
        - http: POST UserEvents
  assign-edu-group:
      name: Discourse-AssignEduGroup
      handler: handler.assign_edu_group
      timeout: 30
      events:
        - schedule: rate(24 hours)
  send-edu-discourse-invites:
      name: Discourse-SendEduDiscourse
      handler: handler.send_edu_discourse_invites
      timeout: 30
      events:
        - schedule: rate(24 hours)
  import-twin4j:
      name: Discourse-ImportTWIN4j
      handler: handler.import_twin4j
      events:
        - schedule: cron(0 9 ? * 7 *)
  update-profile:
      name: Discourse-UpdateProfileWebHook
      handler: handler.update_profile
      timeout: 30
      events:
        - http: POST UpdateProfile
  update-topics:
      name: Discourse-UpdateTopics
      handler: handler.update_topics
      events:
        - schedule: rate(1 hour)
  fetch-medium-posts:
      name: Discourse-FetchMediumPosts
      handler: handler.fetch_medium_posts
      events:
        - schedule: rate(10 minutes)
  post-medium-to-discourse:
      name: Discourse-PostMediumToDiscourse
      handler: handler.post_medium_to_discourse
      events:
        - schedule: rate(5 minutes)

package:
  exclude:
    - node_modules/**
    - a/**
    - .git/**
